Repository funidata/fudis-core, pull requests merged in 2025-07, with the labels that each got.

#36 [Documentation]: Fix Yarn link protocol
  core/documentation/development/GettingStarted.mdx
  core/documentation/development/tooling/Symlink.mdx
Labels: chore

#37 [WelcomePage]: Core Welcome page
  core/.storybook/main.js
  core/.storybook/manager.js
  core/.storybook/preview.js
  core/documentation/development/Management.mdx
  core/documentation/introduction/Introduction.mdx
  core/documentation/introduction/Welcome.mdx
  core/src/assets/images/fudis-core-bg.svg
Labels: feature

#40 Bump to version v1.0.2
  core/package-lock.json
  core/package.json
  package-lock.json
  package.json
  tests/package-lock.json
  tests/package.json
Labels: exclude from release notes
