Repository funidata/fudis-core, pull requests merged in 2025-06, with the labels that each got.

#26 [Components, Icon, Documentation]: Create class based icons, add missing icons to components and documentation to HTML-structures in stories
  core/.storybook/preview.js
  core/_index.scss
  core/src/components/alert/alert.stories.js
  core/src/components/button/button.scss
  core/src/components/button/button.stories.js
  core/src/components/button/icon-button.stories.js
  core/src/components/checkbox-group/checkbox-group.stories.js
  core/src/components/checkbox/checkbox.scss
  core/src/components/checkbox/checkbox.stories.js
  core/src/components/error-summary/error-summary.scss
  core/src/components/error-summary/error-summary.stories.js
  core/src/components/guidance/guidance.scss
  core/src/components/icon/icon.scss
  core/src/components/icon/icon.stories.js
  core/src/components/link/link.scss
  core/src/components/notification/notification.stories.js
  core/src/components/radio-button-group/radio-button-group.stories.js
  core/src/components/radio-button/radio-button.stories.js
  core/src/components/text-area/text-area.stories.js
  core/src/components/text-input/text-input.stories.js
  tests/visual-regression/button.spec.ts
Labels: feature

#29 [Release workflow]: Adjust npm version query
  .github/workflows/release_new_version.yaml
Labels: github actions

#30 Bump to version 0.0.4
  core/package-lock.json
  core/package.json
  package-lock.json
  package.json
  tests/package-lock.json
  tests/package.json
Labels: exclude from release notes

#32 [Guidance, Label, Fieldset]: Remove custom Guidance styles, transfer changed Label and Fieldset styles from Fudis
  core/.storybook/main.js
  core/package-lock.json
  core/package.json
  core/src/components/checkbox-group/checkbox-group.stories.js
  core/src/components/checkbox/checkbox.stories.js
  core/src/components/fieldset/fieldset.scss
  core/src/components/guidance/guidance.scss
  core/src/components/label/label.scss
  core/src/components/radio-button-group/radio-button-group.stories.js
  core/src/components/radio-button/radio-button.stories.js
  core/src/components/text-area/text-area.stories.js
  core/src/components/text-input/text-input.stories.js
  core/storybook-utils.js
  package-lock.json
  tests/visual-regression/checkbox-group.spec.ts-snapshots/checkbox-group-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/checkbox-group.spec.ts-snapshots/checkbox-group-Mobile-Chrome-linux.png
  tests/visual-regression/checkbox-group.spec.ts-snapshots/checkbox-group-Mobile-Safari-linux.png
  tests/visual-regression/checkbox-group.spec.ts-snapshots/checkbox-group-chromium-linux.png
  tests/visual-regression/checkbox-group.spec.ts-snapshots/checkbox-group-firefox-linux.png
  tests/visual-regression/checkbox-group.spec.ts-snapshots/checkbox-group-webkit-linux.png
  tests/visual-regression/checkbox.spec.ts-snapshots/checkbox-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/checkbox.spec.ts-snapshots/checkbox-Mobile-Chrome-linux.png
  tests/visual-regression/checkbox.spec.ts-snapshots/checkbox-Mobile-Safari-linux.png
  tests/visual-regression/checkbox.spec.ts-snapshots/checkbox-chromium-linux.png
  tests/visual-regression/checkbox.spec.ts-snapshots/checkbox-firefox-linux.png
  tests/visual-regression/checkbox.spec.ts-snapshots/checkbox-webkit-linux.png
  tests/visual-regression/radio-button-group.spec.ts-snapshots/radio-button-group-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/radio-button-group.spec.ts-snapshots/radio-button-group-Mobile-Chrome-linux.png
  tests/visual-regression/radio-button-group.spec.ts-snapshots/radio-button-group-Mobile-Safari-linux.png
  tests/visual-regression/radio-button-group.spec.ts-snapshots/radio-button-group-chromium-linux.png
  tests/visual-regression/radio-button-group.spec.ts-snapshots/radio-button-group-firefox-linux.png
  tests/visual-regression/radio-button-group.spec.ts-snapshots/radio-button-group-webkit-linux.png
  tests/visual-regression/radio-button.spec.ts-snapshots/radio-button-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/radio-button.spec.ts-snapshots/radio-button-Mobile-Chrome-linux.png
  tests/visual-regression/radio-button.spec.ts-snapshots/radio-button-Mobile-Safari-linux.png
  tests/visual-regression/radio-button.spec.ts-snapshots/radio-button-chromium-linux.png
  tests/visual-regression/radio-button.spec.ts-snapshots/radio-button-firefox-linux.png
  tests/visual-regression/radio-button.spec.ts-snapshots/radio-button-webkit-linux.png
  tests/visual-regression/text-area.spec.ts-snapshots/text-area-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/text-area.spec.ts-snapshots/text-area-Mobile-Chrome-linux.png
  tests/visual-regression/text-area.spec.ts-snapshots/text-area-Mobile-Safari-linux.png
  tests/visual-regression/text-area.spec.ts-snapshots/text-area-chromium-linux.png
  tests/visual-regression/text-area.spec.ts-snapshots/text-area-firefox-linux.png
  tests/visual-regression/text-area.spec.ts-snapshots/text-area-webkit-linux.png
  tests/visual-regression/text-input.spec.ts-snapshots/text-input-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/text-input.spec.ts-snapshots/text-input-Mobile-Chrome-linux.png
  tests/visual-regression/text-input.spec.ts-snapshots/text-input-Mobile-Safari-linux.png
  tests/visual-regression/text-input.spec.ts-snapshots/text-input-chromium-linux.png
  tests/visual-regression/text-input.spec.ts-snapshots/text-input-firefox-linux.png
  tests/visual-regression/text-input.spec.ts-snapshots/text-input-webkit-linux.png
Labels: breaking change

#34 [Github]: Fix GitHub release notes categories
  .github/release.yml
  core/src/components/alert/alert.scss
  core/src/components/tab-navigation/tab-navigation.scss
  tests/visual-regression/tab-navigation.spec.ts-snapshots/tab-navigation-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/tab-navigation.spec.ts-snapshots/tab-navigation-Mobile-Chrome-linux.png
  tests/visual-regression/tab-navigation.spec.ts-snapshots/tab-navigation-Mobile-Safari-linux.png
  tests/visual-regression/tab-navigation.spec.ts-snapshots/tab-navigation-chromium-linux.png
  tests/visual-regression/tab-navigation.spec.ts-snapshots/tab-navigation-firefox-linux.png
  tests/visual-regression/tab-navigation.spec.ts-snapshots/tab-navigation-webkit-linux.png
Labels: github actions
