Repository funidata/fudis-core, pull requests merged in 2025-08, with the labels that each got.

#44 [StorybookControls]: Improving storybook controls documentation
  core/.storybook/main.js
  core/.storybook/preview.js
  core/documentation/introduction/Welcome.mdx
  core/src/components/alert/alert.stories.js
  core/src/components/badge/badge.stories.js
  core/src/components/button/button.stories.js
  core/src/components/button/icon-button.stories.js
  core/src/components/checkbox-group/checkbox-group.stories.js
  core/src/components/checkbox/checkbox.stories.js
  core/src/components/error-summary/error-summary.stories.js
  core/src/components/horizontal-rule/horizontal-rule.stories.js
  core/src/components/icon/icon.scss
  core/src/components/icon/icon.stories.js
  core/src/components/link/link.stories.js
  core/src/components/loading-spinner/loading-spinner.stories.js
  core/src/components/notification/notification.stories.js
  core/src/components/popover/popover.stories.js
  core/src/components/radio-button-group/radio-button-group.stories.js
  core/src/components/radio-button/radio-button.stories.js
  core/src/components/tab-navigation/tab-navigation.stories.js
  core/src/components/text-area/text-area.stories.js
  core/src/components/text-input/text-input.stories.js
  core/src/foundations/typography/body-text.stories.js
  core/src/foundations/typography/heading.stories.js
  core/storybook-utils.js
  tests/visual-regression/button.spec.ts-snapshots/button-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/button.spec.ts-snapshots/button-Mobile-Chrome-linux.png
  tests/visual-regression/button.spec.ts-snapshots/button-Mobile-Safari-linux.png
  tests/visual-regression/button.spec.ts-snapshots/button-chromium-linux.png
  tests/visual-regression/button.spec.ts-snapshots/button-firefox-linux.png
  tests/visual-regression/button.spec.ts-snapshots/button-webkit-linux.png
  tests/visual-regression/error-summary.spec.ts
  tests/visual-regression/horizontal-rule.spec.ts
  tests/visual-regression/icon.spec.ts
  tests/visual-regression/icon.spec.ts-snapshots/icon-rotate-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icon-rotate-Mobile-Chrome-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icon-rotate-Mobile-Safari-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icon-rotate-chromium-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icon-rotate-firefox-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icon-rotate-webkit-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icons-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icons-Mobile-Chrome-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icons-Mobile-Safari-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icons-chromium-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icons-firefox-linux.png
  tests/visual-regression/icon.spec.ts-snapshots/icons-webkit-linux.png
  tests/visual-regression/loading-spinner.spec.ts-snapshots/loading-spinner-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/loading-spinner.spec.ts-snapshots/loading-spinner-Mobile-Chrome-linux.png
  tests/visual-regression/loading-spinner.spec.ts-snapshots/loading-spinner-Mobile-Safari-linux.png
  tests/visual-regression/loading-spinner.spec.ts-snapshots/loading-spinner-chromium-linux.png
  tests/visual-regression/loading-spinner.spec.ts-snapshots/loading-spinner-firefox-linux.png
  tests/visual-regression/loading-spinner.spec.ts-snapshots/loading-spinner-webkit-linux.png
  tests/visual-regression/popover.spec.ts
Labels: chore

#50 [Chore]: Fix paths from landing page
  landing-page/index.html
Labels: exclude from release notes

#51 Create redirect objects in /core child paths when publishing latest docs
  .github/workflows/release_new_version.yaml
Labels: exclude from release notes, github actions

#46 [Debendabot]: Updated configuration
  .github/dependabot.yml
  .github/workflows/publish_docs_from_pr.yaml
Labels: chore
