Repository funidata/fudis-core, pull requests merged in 2025-09, with the labels that each got.

#57 [Debendabot]:Ignore debendabot on publish docs
  .github/workflows/publish_docs_from_pr.yaml
Labels: exclude from release notes

#59 [Breadcrumbs]: Add component styles
  core/.storybook/preview.js
  core/_styles.scss
  core/src/components/breadcrumbs/breadcrumbs.scss
  core/src/components/breadcrumbs/breadcrumbs.stories.js
  tests/visual-regression/breadcrumbs.spec.ts
  tests/visual-regression/breadcrumbs.spec.ts-snapshots/breadcrumbs-Mobile-Chrome-Big-Landscape-linux.png
  tests/visual-regression/breadcrumbs.spec.ts-snapshots/breadcrumbs-Mobile-Chrome-linux.png
  tests/visual-regression/breadcrumbs.spec.ts-snapshots/breadcrumbs-Mobile-Safari-linux.png
  tests/visual-regression/breadcrumbs.spec.ts-snapshots/breadcrumbs-chromium-linux.png
  tests/visual-regression/breadcrumbs.spec.ts-snapshots/breadcrumbs-firefox-linux.png
  tests/visual-regression/breadcrumbs.spec.ts-snapshots/breadcrumbs-webkit-linux.png
Labels: feature

#71 [RadioButton, Checkbox]: Missing background color
  core/src/components/checkbox/checkbox.scss
  core/src/components/radio-button/radio-button.scss
Labels: bug fix
